[project]
name = "pulse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Joshua Lizana", email = "josh.lizana@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
pulse = "pulse:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
